#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/dvcz
  
  rm -rf build/* tmp/* 
  
  pySloc -L py dvc_add_user dvc_commit dvc_commit_old -X cover -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
