#!/usr/bin/python3
#
# ~/dev/py/dvcz/dvc_bkp1u

"""
Create a project BuildList and post project files to the committer's
subdirectory of in/ in DVCZ's content-keyed store.

If we are not in a project directory (one with a .dvcz/ subdirectory) we
search upward to find one and then make that our working directory.
"""

import os
import sys
from argparse import ArgumentParser

from buildlist import(BuildList,
                      check_dirs_in_path, generate_rsa_key, rm_f_dir_contents)
from optionz import dump_options
from xlattice import (check_using_sha, parse_using_sha, fix_using_sha,
                      show_using_sha)
from xlattice.util import get_exclusions, timestamp_now
from dvcz import(__version__, __version_date__, dvc_get_project_info)


def doit(options):
    """
    Given the command-line options, create the BuildList.

    Optionally serialize the BuildList, append to a log, and populate
    the content-keyed store using the selected SHA hash type.

    """
    data_dir = options.data_dir
    dvcz_dir = options.dvcz_dir
    excl = options.excl
    key_path = options.key_path
    list_file = options.list_file
    logging = options.logging
    title = options.title
    u_path = options.u_path      # if None, don't save to u_path
    using_sha = options.using_sha

    blist = BuildList.list_gen(title, data_dir, dvcz_dir, list_file, key_path,
                               excl, logging, u_path, using_sha)

    print("BuildList written to %s" % os.path.join(dvcz_dir, list_file))

    # confirm that whatever is in the BuildList is now in u_path
    if u_path:
        unmatched = blist.tree.check_in_u_dir(u_path)
        if unmatched:
            for unm in unmatched:
                print("NOT IN UDIR: ", unm)


def get_args():
    """ Collect command-line arguments. """

    now = timestamp_now()
    app_name = 'dvc_bkp2u %s' % __version__

    # parse the command line ----------------------------------------

    desc = 'generate build list for directory, optionally populating u_path'
    parser = ArgumentParser(description=desc)

    # notice that the default is NOT determined by dvcz_dir
    parser.add_argument('-b', '--list_file', default='.dvcz/lastBuildList',
                        help='path to build list'
                        '(default=.dvcz/lastBuildList)')

    parser.add_argument('-D', '--dvcz_dir', default='.dvcz',
                        help='dvcz directory (default=.dvcz)')

    parser.add_argument('-d', '--data_dir', default='../',
                        help='data directory for build list (default=../)')

    parser.add_argument('-i', '--ignore_file', default='.dvczignore',
                        help='file containing wildcards (globs) '
                        'for files to ignore\ndefault=.dvczignore')

    parser.add_argument('-j', '--just_show', action='store_true',
                        help='show options and exit')

    parser.add_argument('-k', '--key_path',
                        help='path to RSA private key for signing')

    parser.add_argument('-L', '--logging', action='store_false',
                        help='append timestamp and BuildList hash to to '
                        'DVCZ_DIR/builds')

    # NOT CURRENTLY SUPPORTED (may never be)
    parser.add_argument('-M', '--match_pat', action='append',
                        help='include only files matching this pattern')

    parser.add_argument('-P', '--project',
                        help='project name')

    # XXX CURRENTLY IGNORED
    parser.add_argument('-s', '--signing', action='store_false',
                        help="add a digital signature -- selected means False")

    parser.add_argument('-T', '--testing', action='store_true',
                        help='this is a test run')

    parser.add_argument('-t', '--title',
                        help='title for build list')

    parser.add_argument('-V', '--showVersion', action='store_true',
                        help='display version number and exit')

    # -1,-2,-3, using_sha, -v/--verbose
    parse_using_sha(parser)

    parser.add_argument(
        '-X', '--exclusions', action='append',
        help='do not include files/directories matching this pattern')

    args = parser.parse_args()

    if args.showVersion:
        print(app_name)
        sys.exit(0)

    args.app_name = app_name
    args.now = now
    return parser, args


def check_sanity(parser, args):
    """ check for options that just don't make sense. """

    if not args.just_show:
        check_using_sha(args.using_sha)

        if (not args.data_dir) or (args.data_dir == ''):
            print("no data directory specified")
            parser.print_usage()
            sys.exit(1)

        if not os.path.isdir(args.data_dir):
            print("data directory '%s' isn't a directory" % args.data_dir)
            parser.print_usage()        # short form
            # parser.print_help()       # long form (what you get from -h)
            sys.exit(1)

        if args.testing:
            args.key_path = os.path.join(args.dvcz_dir, 'skPriv.pem')

        if not os.path.exists(args.key_path):
            check_dirs_in_path(args.key_path)
            if args.testing:
                generate_rsa_key(args.key_path, 1024)
            else:
                generate_rsa_key(args.key_path, 2048)


def check_args(parser, args):
    """ Check and possibly edit command-line arguments. """

    fix_using_sha(args)

    args.cur_dir = os.getcwd()
    if os.path.exists(args.ignore_file):
        args.excl = get_exclusions(args.cur_dir)
    else:
        print("WARNING: ignore file '%s' NOT FOUND" % args.ignore_file)
        args.excl = []
    if not 'build' in args.excl:
        args.excl.append('build')

    if args.exclusions:
        args.excl.extend(args.exclusions)

    if args.testing:
        args.dvcz_dir = os.path.join('tmp/dvcz')
        if os.path.exists(args.dvcz_dir):
            rm_f_dir_contents(args.dvcz_dir)      # empties the directory
    os.makedirs(args.dvcz_dir, 0o755, exist_ok=True)
    # WE HAVE args.dvcz_dir

    check_sanity(parser, args)

    # u_path ------------------------------------------------
    if args.testing and args.u_path:
        if args.u_path[0] == '/':
            args.u_path = args.u_path[1:]
        args.u_path = os.path.join('tmp', args.u_path)
        if os.path.exists(args.u_path):
            rm_f_dir_contents(args.u_path)

    if args.u_path:
        os.makedirs(args.u_path, 0o755, exist_ok=True)

    # committer and in_path -------------------------------

    # The directory at u_path is known to exist.  We are committing to
    # a committer-specific subdirectory, u_path/in/ID, where ID is a
    # 40- or 64-char hex value, the committer's ID.

    # title -----------------------------------------------
    if not args.title:
        args.title = "%s_v%s" % (args.project, __version__)


def show_args(args):
    """
    Conditionally display sorted option names and values.

    Where the option value is list, display the value separately
    under the capitalized option name.
    """
    if args.verbose or args.just_show:
        print("%s %s\n" % (args.app_name, __version_date__))

    if args.verbose or args.just_show:
        print(dump_options(args))

    if args.just_show:
        sys.exit(0)


def main():
    """
    Collect comamnd line options and execute the command if required.
    """

    parser, args = get_args()
    dvc_get_project_info(args)      # and possibly change working directory
    check_args(parser, args)
    show_args(args)

    # do what's required --------------------------------------------

    # try: ACQUIRE LOCK ON PROJECT, that is, on the name of the project
    doit(args)

    # finally: RELEASE LOCK ON PROJECT

if __name__ == '__main__':
    main()
