[meta]
version = "0.1.0"

[project]
name = "dvcz"
package = "dvcz"
main_lang = "py"
version = "0.1.23"
version_date = "2018-03-07"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
description = "distributed version control system"
copyright = "2016-2017"
dev_status = "pre-alpha"
license = "mit"
relpath = "py/dvcz"
state = "shared"
url = "https://jddixon.github.io/dvcz"

[py]
packages = [ "dvcz",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = []
ext_modules = []
distshare = [ "buildlist", "optionz", "rnglib", "xlattice_py",]
requirements = [ "pycrypt", "pysha3", "setuptools",]
test_requirements = []
